### ISSUE TITLE
Can't see post cards on home..

### ISSUE THREAD

**Issue by bkim9324** [Reedyn/Saga#48]
I can't see any of post cards on main page after self-hosted..it was okay on local address. any help?

**Comment by Reedyn** [comment]
Can you send me a link of your site so I can have a look?

**Comment by bkim9324** [comment]
http://ec2-54-64-28-241.ap-northeast-1.compute.amazonaws.com/

**Comment by bkim9324** [comment]
a post card is invisible though it's clickable..

**Comment by Reedyn** [comment]
It's an issue with your ghostblog not being configured to the correct domain (it's currently configured to  http://my-ghost-blog.com/).

The issue arises because I've used a workaround for loading in scripts as they are needed but it depends on the blog being configured correctly, when the same-domain public API gets opened up I will be using that instead of this temporary workaround. 

**For now you can fix your problem by simply configuring the domain. [A simple guide for doing this can be found on the official Ghost support](http://support.ghost.org/config/)**

**Comment by bkim9324** [comment]
super thanks for the explain! :)

**Comment by Reedyn** [comment]
No worries! Thanks for using the theme. Let me know if you have any other issues or if you have something you'd like to see 😀
