### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by pointcache** [Reedyn/Saga#95]

**Comment by pointcache** [comment]
Where is the navigation? I dont see any navigation anywhere how do you yourself use the website that is unable to display navigation? Im just curious what can be the thought process behind that.

**Comment by pointcache** [comment]
anyway its so bugged its unusable anyway

**Comment by Reedyn** [comment]
First. In a way the project is on a hiatus due to a few reasons. 1. I don't have as much spare time as I did when I initially developed it (You're free to fork it and develop it yourself). 2. My next version of the theme is intended to have a few features that still rely on Ghost developing the support for those features in the first place. So I'm kind of waiting for that.

Second question, no there is no current support for navigation. The theme was developed initially before the first navigation support for Ghost was released. The next version will have support for that in some form. Also the icon navigation isn't compatible with the new navigation system so it will have to be redesigned from the ground up.

Third question, how did you download the theme? Did you use the project download button for GitHub or did you download one of the stable releases? Cause one is an unstable project file the other is a release inteded for production usage. My own website is currently running under the latest release without much issue.

**Comment by maxcr** [comment]
Well I've been developing my own fork. I've solved all the navigation issues and pretty much all the bugs with the theme. I'll release it in a little bit. stay posted.

Its at gitlab.maxrobbins.com Its currently private so you cannot see it but I'll make it public in the next few days.

**Comment by pointcache** [comment]
@maxcr thank you, im not a web dev so i would be able to do anything at all with the theme.
im literally a dirty user.

**Comment by maxcr** [comment]
https://gitlab.maxrobbins.com/maxcr/Journey

Here's my fork. I upgraded a bunch of stuff. Added a working menu. Reedy let me know if you want a pull request.

**Comment by Reedyn** [comment]
It's not abandoned per say but I'm not actively developing it due to lack of time. I will only develop it for my own needs which at the moment aren't huge.

As I've said before, feel free to fork and do whatever you please with what I've written so far. As @maxcr has done above =)
